#!/usr/bin/env bash
# Install the web server 'nginx' on the server
sudo apt-get update
sudo apt-get install nginx
ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

# check configuration
sudo nginx -t

sudo service nginx start
sudo service nginx reload
