#!/usr/bin/env bash
# configure HAProxy on lb-01 server
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  erdey2_frontend
        bind *:80
        mode http
        default_backend erdey2_backend
backend erdey2_backend
        balance roundrobin
        server 491430-web-01 54.89.179.236:80 check
        server 491430-web-02 54.237.30.31:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the Nginx service
sudo service haproxy restart
