#!/usr/bin/env bash
# configure nginx to listen on port 80
# remove the default nginx configuration
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart the engine
restart nginx restart
