#!/usr/bin/env bash
sudo nano /etc/sysctl.conf
net.ipv4.ip_forward=1
sudo sysct1 -p
sudo iptables -t nat -A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80
sudo apt-get install iptables-persistent
sudo netfilter-persistent save
sudo netfilter-persistent reload
suso ufw allow 80/tcp
sudo ufw allow 8080/tcp
